# Generated by Django 3.0.6 on 2020-07-27 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('image', models.ImageField(help_text='Фотография должна иметь размеры 60px x 60px для корректного отображения на сайте!', upload_to='review/%Y/%m/%d', verbose_name='Фотография')),
                ('message', models.TextField(max_length=2048, verbose_name='Отзыв')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность отзыва')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
