# Generated by Django 3.0.6 on 2020-07-27 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Фотография должна иметь размеры 270px x 300px дл корректного отображения на сайте!', upload_to='instagram/%Y/%m/%d', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Фотография к инстаграму',
                'verbose_name_plural': 'Фотографии к инстаграму',
            },
        ),
    ]
