# Generated by Django 3.0.6 on 2020-07-28 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20200727_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя покупатея')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия покупателя')),
                ('email', models.EmailField(max_length=50, verbose_name='Е-мейл покупателя')),
                ('phone', models.CharField(default=None, max_length=50, verbose_name='Номер телефона покупателя')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес покупателя')),
                ('postal_code', models.CharField(max_length=9, verbose_name='Почтовый индекс')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('paid', models.BooleanField(default=False, verbose_name='Заказ оплачен')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Лот заказа',
                'verbose_name_plural': 'Лот заказа',
            },
        ),
    ]
