# Generated by Django 3.0.6 on 2020-07-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200728_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=256, verbose_name='Пожелание к заказу'),
        ),
    ]
