# Generated by Django 3.0.6 on 2020-07-27 11:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование товара')),
                ('slug', models.SlugField(max_length=200, verbose_name='Уникальная строка')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('code', models.CharField(blank=True, db_index=True, default=None, max_length=6, verbose_name='Код товара')),
                ('vendor_code', models.CharField(blank=True, db_index=True, default=None, max_length=6, verbose_name='Артикул')),
                ('discount', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка на товар в %')),
                ('image', models.ImageField(blank=True, upload_to='product_covers/%Y/%m/%d', verbose_name='Обложка товара')),
                ('hot_deal', models.BooleanField(default=None, verbose_name='Товар спец. предложения')),
                ('hot_sales', models.BooleanField(default=None, verbose_name='Хит продаж')),
                ('as_new', models.BooleanField(default=None, verbose_name='Новое поступление')),
                ('recommended', models.BooleanField(default=None, verbose_name='Рекомендуемые магазином')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-created', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=512, verbose_name='Подкатегория товара')),
                ('slug', models.SlugField(max_length=200, verbose_name='Уникальная строка')),
                ('image', models.ImageField(blank=True, upload_to='category/%Y/%m/%d', verbose_name='Обложка категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие в магазине')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.ProductCategory', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Статус товара')),
                ('slug', models.SlugField(max_length=200, verbose_name='Уникальная строка')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие в магазине')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата созд-ия записи')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Статус товара',
                'verbose_name_plural': 'Статус товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=512, verbose_name='Наименование категории')),
                ('slug', models.SlugField(max_length=200, verbose_name='Уникальная строка')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие в магазине')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность статуса')),
                ('image', models.ImageField(blank=True, upload_to='special_category_covers/%Y/%m/%d', verbose_name='Обложка категории')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Описание категории')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.ProductCategory', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('name', 'created'),
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная фотография')),
                ('is_not_main', models.BooleanField(default=False, verbose_name='Доп. фотография')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Подробная информация к товару',
                'verbose_name_plural': 'Подробная информация к товарам',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductCategory', verbose_name='Категория товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductSpecialCategory', verbose_name='Кат-я спец. назн-ия'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductStatus', verbose_name='Статус'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
