# Generated by Django 3.0.6 on 2020-07-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='special_category',
        ),
        migrations.DeleteModel(
            name='ProductSpecialCategory',
        ),
    ]
