# Generated by Django 3.0.8 on 2020-08-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200729_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория товаров', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Память уст-ва'),
        ),
    ]
